version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ts-loader
    versions:
    - 9.0.0
    - 9.1.0
  - dependency-name: "@wordpress/babel-preset-default"
    versions:
    - 5.0.0
    - 5.0.1
    - 5.1.0
    - 5.2.0
