# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Webpack Helpers
description: Human Made's toolkit for modern frontend asset bundling.
author: Human Made
baseurl: "/webpack-helpers" # the subpath of your site, e.g. /blog
url: "https://humanmade.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/icons/hm-logo.svg"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/favicon/favicon.ico"

# Theme settings
theme: just-the-hm-docs
color_scheme: hm
permalink: pretty

# Aux links for the upper right navigation
aux_links:
  Human Made:
    - "//humanmade.com"
  Webpack-Helpers on GitHub:
    - "//github.com/humanmade/webpack-helpers"

callouts_level: quiet # or loud
callouts_opacity: 0.3
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: hm-purple-callout
  new:
    title: New
    color: hm-mint-callout
  note:
    title: Note
    color: hm-blue-callout
  warning:
    title: Warning
    color: hm-red-callout
